;;; support-mwsedic.el --- suport file for "MWSEDIC" EPWING version.

;; This program is free software; you can redistribute it and/or
;; modify it under the terms of the GNU General Public License
;; as published by the Free Software Foundation; either version 2
;; of the License, or (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program; if not, write to the Free Software Foundation,
;; Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

;;; Code:

(require 'lookup)

(let 
  ((encoded-mwsedic-gaiji-table
    '(
      ("ha121" "á")
      ("zb021" "鄧")
      ("zb024" "æ")
      ;;("zb025" "-")   ;;
      ("zb026" "ǽ")

      ("ha121" " ")
      ("ha122" "¡")
      ("ha123" "¢")
      ("ha124" "£")
      ("ha125" "¤")
      ("ha126" "¥")
      ("ha127" "¦")
      ("ha128" "§")
      ("ha129" "¨")
      ("ha12a" "©")
      ("ha12b" "ª")
      ("ha12c" "«")
      ("ha12d" "¬")
      ("ha12e" "­")
      ("ha12f" "®")
      ("ha130" "¯")
      ("ha131" "°")
      ("ha132" "±")
      ("ha133" "²")
      ("ha134" "³")
      ("ha135" "´")
      ("ha136" "µ")
      ("ha137" "¶")
      ("ha138" "·")
      ("ha139" "¸")
      ("ha13a" "¹")
      ("ha13b" "º")
      ("ha13c" "»")
      ("ha13d" "¼")
      ("ha13e" "½")
      ("ha13f" "¾")
      ("ha140" "¿")
      ("ha141" "À")
      ("ha142" "Á")
      ("ha143" "Â")
      ("ha144" "Ã")
      ("ha145" "Ä")
      ("ha146" "Å")
      ("ha147" "Æ")
      ("ha148" "Ç")
      ("ha149" "È")
      ("ha14a" "É")
      ("ha14b" "Ê")
      ("ha14c" "Ë")
      ("ha14d" "Ì")
      ("ha14e" "Í")
      ("ha14f" "Î")
      ("ha150" "Ï")
      ("ha151" "Ð")
      ("ha152" "Ñ")
      ("ha153" "Ò")
      ("ha154" "Ó")
      ("ha155" "Ô")
      ("ha156" "Õ")
      ("ha157" "Ö")
      ("ha158" "×")
      ("ha159" "Ø")
      ("ha15a" "Ù")
      ("ha15b" "Ú")
      ("ha15c" "Û")
      ("ha15d" "Ü")
      ("ha15e" "Ý")
      ("ha15f" "Þ")
      ("ha160" "ß")
      ("ha161" "à")
      ("ha162" "á")
      ("ha163" "â")
      ("ha164" "ã")
      ("ha165" "ä")
      ("ha166" "å")
      ("ha167" "æ")
      ("ha168" "ç")
      ("ha169" "è")
      ("ha16a" "é")
      ("ha16b" "ê")
      ("ha16c" "ë")
      ("ha16d" "ì")
      ("ha16e" "í")
      ("ha16f" "î")
      ("ha170" "ï")
      ("ha171" "ð")
      ("ha172" "ñ")
      ("ha173" "ò")
      ("ha174" "ó")
      ("ha175" "ô")
      ("ha176" "õ")
      ("ha177" "ö")
      ("ha178" "÷")
      ("ha179" "ø")
      ("ha17a" "ù")
      ("ha17b" "ú")
      ("ha17c" "û")
      ("ha17d" "ü")
      ("ha17e" "ý")
      ("ha221" "þ")
      ("ha222" "ÿ")
      ("ha223" "Ā")
      ("ha224" "ā")
      ("ha225" "Ă")
      ("ha226" "ă")
      ("ha227" "Ą")
      ("ha228" "ą")
      ("ha229" "Ć")
      ("ha22a" "ć")
      ("ha22b" "Ĉ")
      ("ha22c" "ĉ")
      ("ha22d" "Ċ")
      ("ha22e" "ċ")
      ("ha22f" "Č")
      ("ha230" "č")
      ("ha231" "Ď")
      ("ha232" "ď")
      ("ha233" "Đ")
      ("ha234" "đ")
      ("ha235" "Ē")
      ("ha236" "ē")
      ("ha237" "Ĕ")
      ("ha238" "ĕ")
      ("ha239" "Ė")
      ("ha23a" "ė")
      ("ha23b" "Ę")
      ("ha23c" "ę")
      ("ha23d" "Ě")
      ("ha23e" "ě")
      ("ha23f" "Ĝ")
      ("ha240" "ĝ")
      ("ha241" "Ğ")
      ("ha242" "ğ")
      ("ha243" "Ġ")
      ("ha244" "ġ")
      ("ha245" "Ģ")
      ("ha246" "ģ")
      ("ha247" "Ĥ")
      ("ha248" "ĥ")
      ("ha249" "Ħ")
      ("ha24a" "ħ")
      ("ha24b" "Ĩ")
      ("ha24c" "ĩ")
      ("ha24d" "Ī")
      ("ha24e" "ī")
      ("ha24f" "Ĭ")
      ("ha250" "ĭ")
      ("ha251" "Į")
      ("ha252" "į")
      ("ha253" "İ")
      ("ha254" "ı")
      ("ha255" "Ĳ")
      ("ha256" "ĳ")
      ("ha257" "Ĵ")
      ("ha258" "ĵ")
      ("ha259" "Ķ")
      ("ha25a" "ķ")
      ("ha25b" "ĸ")
      ("ha25c" "Ĺ")
      ("ha25d" "ĺ")
      ("ha25e" "Ļ")
      ("ha25f" "ļ")
      ("ha260" "Ľ")
      ("ha261" "ľ")
      ("ha262" "Ŀ")
      ("ha263" "ŀ")
      ("ha264" "Ł")
      ("ha265" "ł")
      ("ha266" "Ń")
      ("ha267" "ń")
      ("ha268" "Ņ")
      ("ha269" "ņ")
      ("ha26a" "Ň")
      ("ha26b" "ň")
      ("ha26c" "ŉ")
      ("ha26d" "Ŋ")
      ("ha26e" "ŋ")
      ("ha26f" "Ō")
      ("ha270" "ō")
      ("ha271" "Ŏ")
      ("ha272" "ŏ")
      ("ha273" "Ő")
      ("ha274" "ő")
      ("ha275" "Œ")
      ("ha276" "œ")
      ("ha277" "Ŕ")
      ("ha278" "ŕ")
      ("ha279" "Ŗ")
      ("ha27a" "ŗ")
      ("ha27b" "Ř")
      ("ha27c" "ř")
      ("ha27d" "Ś")
      ("ha27e" "ś")
      ("ha321" "Ŝ")
      ("ha322" "ŝ")
      ("ha323" "Ş")
      ("ha324" "ş")
      ("ha325" "Š")
      ("ha326" "š")
      ("ha327" "Ţ")
      ("ha328" "ţ")
      ("ha329" "Ť")
      ("ha32a" "ť")
      ("ha32b" "Ŧ")
      ("ha32c" "ŧ")
      ("ha32d" "Ũ")
      ("ha32e" "ũ")
      ("ha32f" "Ū")
      ("ha330" "ū")
      ("ha331" "Ŭ")
      ("ha332" "ŭ")
      ("ha333" "Ů")
      ("ha334" "ů")
      ("ha335" "Ű")
      ("ha336" "ű")
      ("ha337" "Ų")
      ("ha338" "ų")
      ("ha339" "Ŵ")
      ("ha33a" "ŵ")
      ("ha33b" "Ŷ")
      ("ha33c" "ŷ")
      ("ha33d" "Ÿ")
      ("ha33e" "Ź")
      ("ha33f" "ź")
      ("ha340" "Ż")
      ("ha341" "ż")
      ("ha342" "Ž")
      ("ha343" "ž")
      ("ha344" "ſ")
      ("ha345" "Ǎ")
      ("ha346" "ǎ")
      ("ha347" "Ǐ")
      ("ha348" "ǐ")
      ("ha349" "Ǒ")
      ("ha34a" "ǒ")
      ("ha34b" "Ǔ")
      ("ha34c" "ǔ")
      ("ha34d" "ƒ")
      ("ha34e" "ˆ")
      ("ha34f" "˜")
      ("ha350" "ɔ")
      ;;("ha351" "-")   ;;
      ;;("ha352" "-")   ;;
      ("ha353" "ə")
      ;;("ha354" "-")   ;;
      ;;("ha355" "-")   ;;
      ("ha356" "ʌ")
      ;;("ha357" "-")   ;;
      ;;("ha358" "-")   ;;
      ("ha359" "ː")
      ("ha35a" "ɑ")
      ;;("ha35b" "-")   ;;
      ;;("ha35c" "-")   ;;
      ("ha35d" "ʃ")
      ("ha35e" "ʊ")
      ("ha35f" "θ")
      ("ha360" "ʒ")
      ("ha361" "ɒ")
      ("ha362" "Ḍ")
      ("ha363" "ḍ")
      ("ha364" "ḥ")
      ("ha365" "ḷ")
      ("ha366" "ḹ")
      ("ha367" "ṁ")
      ("ha368" "ṃ")
      ("ha369" "ṅ")
      ("ha36a" "Ṇ")
      ("ha36b" "ṇ")
      ("ha36c" "Ṉ")
      ("ha36d" "ṉ")
      ("ha36e" "Ṛ")
      ("ha36f" "ṛ")
      ("ha370" "Ṝ")
      ("ha371" "ṝ")
      ("ha372" "ṡ")
      ("ha373" "Ṣ")
      ("ha374" "ṣ")
      ("ha375" "Ṭ")
      ("ha376" "ṭ")
      ("ha377" "√")
      ;;("ha378" "-")   ;;	anunasika
      ;;("ha379" "-")   ;;
      ;;("ha37a" "-")   ;;
      ;;("ha37b" "-")   ;;	circ2
      ;;("ha37c" "-")   ;;	circ3
      ;;("ha37d" "-")   ;;	circ4
      )))
  (defconst mwsedic-gaiji-table
    (lookup-new-gaiji-table
     (mapcar 
      '(lambda (x)
        (list
         (if (eq lookup-support-agent 'ndtp)
             (concat "gaiji:" (car x))
           (car x))
         (cadr x)))
      encoded-mwsedic-gaiji-table))))

;; convert input string to Kyoto-Harvard
(defun mwsedic-dev-kyoto-harvard-encode-string (str)
  (with-temp-buffer
    (require 'ind-util)
    (insert str)
    (indian-dev-kyoto-harvard-encode-region (point-min) (point-max))
    (buffer-string)))

(defun mwsedic-dev-kyoto-harvard-decode-string (str)
  (with-temp-buffer
    (require 'ind-util)
    (insert str)
    (indian-dev-kyoto-harvard-decode-region (point-min) (point-max))
    (buffer-string)))

(defun mwsedic-arrange-structure (entry)
  (goto-char (point-min))
  (end-of-line)
  (goto-char (point-min))
  (when (looking-at "[ *]*\\([a-zA-Z]+\\)")
    (goto-char (match-end 0))
    (insert " 《" (mwsedic-dev-kyoto-harvard-decode-string (match-string 1))
            "》")
    (while (re-search-forward "\\[ \\([a-zA-Z^'-]+\\) \\]" nil t)
      (goto-char (match-end 1))
      (insert " 《" (mwsedic-dev-kyoto-harvard-decode-string (match-string 1))
              "》 "))))
                                                            
(defun mwsedic-kyoto-harvard-query-string ()
  "If query-string is Devanagari, convert it to kyoto-harvard."
  (if (string-match "[ँ-ॽ]" lookup-query-string)
      (setq lookup-query-string
            (mwsedic-dev-kyoto-harvard-encode-string lookup-query-string))))

(add-hook 'lookup-query-string-hook 'mwsedic-kyoto-harvard-query-string)

(setq lookup-support-options
      (list :arranges '((structure mwsedic-arrange-structure))
            :gaiji-table mwsedic-gaiji-table))

;;; support-mwsedic.el ends here
